// Action Types
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const SELECT_PRODUCT = "SELECT_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const RECORD_UPDATED = "RECORD_UPDATED";
export const RECORD_ERROR = "RECORD_ERROR";