import IMAGES from '../services/imgWatch.js'

// Data
export const watchSet = [
    {
        "id": 1,
        "brand": "Rolex",
        "model": "Daytona",
        "price": 15000,
        "currency": "USD",
        "case_material": "Stainless Steel",
        "dial_color": "Black",
        "movement": "Automatic",
        "water_resistance": "100m",
        "image_url": IMAGES.img1,
    },
    {
        "id": 2,
        "brand": "Omega",
        "model": "Speedmaster",
        "price": 7000,
        "currency": "USD",
        "case_material": "Titanium",
        "dial_color": "Blue",
        "movement": "Manual",
        "water_resistance": "50m",
        "image_url": IMAGES.img2,
    },
    {
        "id": 3,
        "brand": "Patek Philippe",
        "model": "Nautilus",
        "price": 30000,
        "currency": "USD",
        "case_material": "Rose Gold",
        "dial_color": "White",
        "movement": "Automatic",
        "water_resistance": "120m",
        "image_url": IMAGES.img3,
    },
    {
        "id": 4,
        "brand": "Audemars Piguet",
        "model": "Royal Oak",
        "price": 25000,
        "currency": "USD",
        "case_material": "Stainless Steel",
        "dial_color": "Gray",
        "movement": "Automatic",
        "water_resistance": "50m",
        "image_url": IMAGES.img4,
    },
    {
        "id": 5,
        "brand": "Tag Heuer",
        "model": "Carrera",
        "price": 4500,
        "currency": "USD",
        "case_material": "Stainless Steel",
        "dial_color": "Black",
        "movement": "Automatic",
        "water_resistance": "100m",
        "image_url": IMAGES.img5,
    },
    {
        "id": 6,
        "brand": "Breitling",
        "model": "Navitimer",
        "price": 8000,
        "currency": "USD",
        "case_material": "Stainless Steel",
        "dial_color": "Blue",
        "movement": "Automatic",
        "water_resistance": "30m",
        "image_url": IMAGES.img6,
    },
    {
        "id": 7,
        "brand": "Hublot",
        "model": "Big Bang",
        "price": 12000,
        "currency": "USD",
        "case_material": "Ceramic",
        "dial_color": "Black",
        "movement": "Automatic",
        "water_resistance": "100m",
        "image_url": IMAGES.img7,
    },
    {
        "id": 8,
        "brand": "Cartier",
        "model": "Santos",
        "price": 8500,
        "currency": "USD",
        "case_material": "Gold",
        "dial_color": "White",
        "movement": "Automatic",
        "water_resistance": "100m",
        "image_url": IMAGES.img8,
    },
    {
        "id": 9,
        "brand": "IWC",
        "model": "Portugieser",
        "price": 7000,
        "currency": "USD",
        "case_material": "Stainless Steel",
        "dial_color": "White",
        "movement": "Automatic",
        "water_resistance": "30m",
        "image_url": IMAGES.img9,
    },
    {
        "id": 10,
        "brand": "Panerai",
        "model": "Luminor",
        "price": 9000,
        "currency": "USD",
        "case_material": "Titanium",
        "dial_color": "Black",
        "movement": "Manual",
        "water_resistance": "300m",
        "image_url": IMAGES.img10,
    },
    {
        "id": 11,
        "brand": "Vacheron Constantin",
        "model": "Overseas",
        "price": 20000,
        "currency": "USD",
        "case_material": "Stainless Steel",
        "dial_color": "Blue",
        "movement": "Automatic",
        "water_resistance": "150m",
        "image_url": IMAGES.img11,
    },
    {
        "id": 12,
        "brand": "Jaeger-LeCoultre",
        "model": "Reverso",
        "price": 11000,
        "currency": "USD",
        "case_material": "Stainless Steel",
        "dial_color": "Silver",
        "movement": "Manual",
        "water_resistance": "30m",
        "image_url": IMAGES.img12,
    },
    {
        "id": 13,
        "brand": "Blancpain",
        "model": "Fifty Fathoms",
        "price": 14000,
        "currency": "USD",
        "case_material": "Stainless Steel",
        "dial_color": "Black",
        "movement": "Automatic",
        "water_resistance": "300m",
        "image_url": IMAGES.img13,
    },
    {
        "id": 14,
        "brand": "Breguet",
        "model": "Classique",
        "price": 19000,
        "currency": "USD",
        "case_material": "Rose Gold",
        "dial_color": "Silver",
        "movement": "Automatic",
        "water_resistance": "30m",
        "image_url": IMAGES.img14,
    },
    {
        "id": 15,
        "brand": "Zenith",
        "model": "Defy",
        "price": 7500,
        "currency": "USD",
        "case_material": "Titanium",
        "dial_color": "Skeleton",
        "movement": "Automatic",
        "water_resistance": "100m",
        "image_url": IMAGES.img15,
    },
    {
        "id": 16,
        "brand": "Chopard",
        "model": "Mille Miglia",
        "price": 6500,
        "currency": "USD",
        "case_material": "Stainless Steel",
        "dial_color": "Black",
        "movement": "Automatic",
        "water_resistance": "50m",
        "image_url": IMAGES.img16,
    },
    {
        "id": 17,
        "brand": "Girard-Perregaux",
        "model": "Laureato",
        "price": 10000,
        "currency": "USD",
        "case_material": "Stainless Steel",
        "dial_color": "Blue",
        "movement": "Automatic",
        "water_resistance": "100m",
        "image_url": IMAGES.img17,
    },
    {
        "id": 18,
        "brand": "Richard Mille",
        "model": "RM 11-03",
        "price": 150000,
        "currency": "USD",
        "case_material": "Carbon",
        "dial_color": "Skeleton",
        "movement": "Automatic",
        "water_resistance": "50m",
        "image_url": IMAGES.img18,
    },
    {
        "id": 19,
        "brand": "A. Lange & Söhne",
        "model": "Lange 1",
        "price": 40000,
        "currency": "USD",
        "case_material": "Platinum",
        "dial_color": "Silver",
        "movement": "Manual",
        "water_resistance": "30m",
        "image_url": IMAGES.img19,
    },
    {
        "id": 20,
        "brand": "Piaget",
        "model": "Altiplano",
        "price": 18000,
        "currency": "USD",
        "case_material": "White Gold",
        "dial_color": "White",
        "movement": "Automatic",
        "water_resistance": "30m",
        "image_url": IMAGES.img20,
    },
    {
        "id": 21,
        "brand": "Montblanc",
        "model": "1858",
        "price": 5000,
        "currency": "USD",
        "case_material": "Bronze",
        "dial_color": "Black",
        "movement": "Automatic",
        "water_resistance": "100m",
        "image_url": IMAGES.img21,
    },
    {
        "id": 22,
        "brand": "Ulysse Nardin",
        "model": "Diver",
        "price": 13000,
        "currency": "USD",
        "case_material": "Titanium",
        "dial_color": "Blue",
        "movement": "Automatic",
        "water_resistance": "300m",
        "image_url": IMAGES.img22,
    },
    {
        "id": 23,
        "brand": "Glashütte Original",
        "model": "Senator",
        "price": 9000,
        "currency": "USD",
        "case_material": "Stainless Steel",
        "dial_color": "Silver",
        "movement": "Automatic",
        "water_resistance": "50m",
        "image_url": IMAGES.img23,
    },
    {
        "id": 24,
        "brand": "Bulgari",
        "model": "Octo",
        "price": 12000,
        "currency": "USD",
        "case_material": "Ceramic",
        "dial_color": "Black",
        "movement": "Automatic",
        "water_resistance": "100m",
        "image_url": IMAGES.img24,
    },
    {
        "id": 25,
        "brand": "Parmigiani Fleurier",
        "model": "Tonda",
        "price": 20000,
        "currency": "USD",
        "case_material": "Rose Gold",
        "dial_color": "White",
        "movement": "Automatic",
        "water_resistance": "30m",
        "image_url": IMAGES.img25,
    }
]